# This is the config file for landscape.io
# https://landscape.io/pages/docs
# https://landscape.io/github/gammapy/gammapy/

ignore-paths:
    - dev
    - examples
    - docs/conf.py
    - gammapy/extern
    - gammapy/version.py
    - gammapy/conftest.py
    - gammapy/_astropy_init.py
    - gammapy/cython_version.py

ignore-patterns:
#   *tests*
#   *setup_package*
