#
# This travis-ci build matrix config is a modified copy of the one from Astropy
#


# We can't use `language: python` here because it's not supported on Mac.
# But that's OK ... the language here is irrelevant because we use conda
# to install our own Python.
language: c

os:
    - linux

# This is a signal to travis-ci to use the new build infrastructure
sudo: false

addons:
  apt:
    packages: &default_apt
      - graphviz
      - texlive-latex-extra
      - dvipng

env:
    global:
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=1.1
        - CONDA_DEPENDENCIES='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas pyregion naima photutils wcsaxes'
        - CONDA_DOCS_DEPENDENCIES='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas pyregion naima photutils wcsaxes pygments aplpy'
        - PIP_DEPENDENCIES='uncertainties reproject'
        - SHERPA=false
        - CONDA_CHANNELS='astropy'
        - FETCH_GAMMAPY_EXTRA=true
        - MAIN_CMD='python setup.py'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.3 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'


matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try MacOS X
        - os: osx
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
               CONDA_DEPENDENCIES='Cython click'
               PIP_DEPENDENCIES=''

        # Run tests
        # Coverage is measured on Python 2 (where Sherpa is available)
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test -V --coverage'
               SHERPA=true

        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='test -V'

        # Build docs
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES
               SHERPA=true
        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES

        # Run tests without GAMMAPY_EXTRA available
        - os: linux
          env: FETCH_GAMMAPY_EXTRA=false PYTHON_VERSION=3.4 SETUP_CMD='test -V'

        # Test with Astropy dev and LTS versions
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=lts SETUP_CMD='test -V'
               SHERPA=true
        - os: linux
          env: PYTHON_VERSION=3.4 ASTROPY_VERSION=lts SETUP_CMD='test -V'
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=dev SETUP_CMD='test -V'
               SHERPA=true
        - os: linux
          env: PYTHON_VERSION=3.4 ASTROPY_VERSION=dev SETUP_CMD='test -V'
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=dev SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES
               SHERPA=true
        - os: linux
          env: PYTHON_VERSION=3.4 ASTROPY_VERSION=dev SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES

        # Test with with optional dependencies disabled
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES='Cython click'
               PIP_DEPENDENCIES=''
        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES='Cython click'
               PIP_DEPENDENCIES=''

        # Test with other numpy versions. Not all of the packages are
        # available with these on conda, thus moving some of them to pip
        # install. Latest astropy stable (1.1) is also not available for
        # older numpies, but using lts version should be good enough for
        # these tests (so we can avoid building it from source).
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=dev SETUP_CMD='test -V'
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.9 SETUP_CMD='test -V'
               SHERPA=true ASTROPY_VERSION=lts
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.8 SETUP_CMD='test -V'
               SHERPA=true ASTROPY_VERSION=lts
               CONDA_CHANNELS='astropy-ci-extras astropy'
               CONDA_DEPENDENCIES='Cython click matplotlib'
               PIP_DEPENDENCIES=''

    # You can move builds that temporarily fail because of some non-Gammapy issue here
    # Please add a link to a GH issue that tracks the upstream issue.
    allow_failures:
      - env: PYTHON_VERSION=3.4 NUMPY_VERSION=dev SETUP_CMD='test -V'
      - env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7 SETUP_CMD='test -V'
             SHERPA=true
             CONDA_CHANNELS='astropy-ci-extras astropy'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    - if $FETCH_GAMMAPY_EXTRA; then
          git clone https://github.com/gammapy/gammapy-extra.git $HOME/gammapy-extra;
          export GAMMAPY_EXTRA=${HOME}/gammapy-extra;
      fi

    # This is needed to make matplotlib plot testing work
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          export QT_API=pyqt;
      fi

    # Reinstalling the required numpy version as it may be downgraded
    - if $SHERPA; then
          conda install --yes --channel astropy numpy=$NUMPY_VERSION iminuit;
          conda install --yes --channel https://conda.anaconda.org/cxc/channel/dev sherpa;
          conda install --yes -q numpy=$NUMPY_VERSION;
      fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test -V --coverage' ]]; then
          coveralls --rcfile='gammapy/tests/coveragerc';
      fi
