binning:
  binsz: 0.02
  proj: 'TAN'
  coordsys: 'CEL'
  nxpix: 500
  nypix: 300
  enumbins: 10

pointing:
  ra: 83.63
  dec: 22.01  
  livetime: 1 hour

selection:
  offset_fov: 2
  emin: 0.05
  emax: 100
  ROI: 5 deg

logging:
  working_dir: .

model: 
  source1: 'Crab'
  spectrum1: pl
  pivot_energy1: 1
  prefactor1: 2e-12
  index1: 2.2
  template1: Shell2D
  ra1: 83.63
  dec1: 22.01
  rin1: 0.3
  width1: 0.1
