binning:
  binsz: 0.05
  proj: 'TAN'
  coordsys: 'CEL'
  nxpix: 200
  nypix: 100
  enumbins: 10

pointing:
  ra: 83.63
  dec: 22.01  
  livetime: 3 

selection: 
  offset_fov: 2
  emin: 0.1
  emax: 100
  ROI: 5

loggin:
  working_dir: /Users/roberta/Documents/Projects/CTA/mc/        

model: 
 source1: 'Crab'   
 spectrum1: PL
 pivot_energy1: 1
 prefactor1: 2e-12
 index1: 2.2
 template1: Shell2D
 ra1: 83.63
 dec1: 22.01
 rin1: 1
 width1: 0.02  
