name: astropy

channels:
  - conda-forge
  - astropy

dependencies:
  - python=3
  - cython
  - numpy
  - uncertainties
  - sphinx
  - scipy
  - scikit-image
  - matplotlib
  - astropy
  - regions
  - reproject
  - aplpy
